// Code generated by protoc-gen-go.
// source: storage.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	storage.proto

It has these top-level messages:
	ServerConfig
	TLSCertificate
	File
	MainConfig
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerConfig struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Config []byte            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Tls    *TLSCertificate   `protobuf:"bytes,3,opt,name=tls" json:"tls,omitempty"`
	Meta   map[string]string `protobuf:"bytes,4,rep,name=meta" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Files  []*File           `protobuf:"bytes,5,rep,name=files" json:"files,omitempty"`
}

func (m *ServerConfig) Reset()                    { *m = ServerConfig{} }
func (m *ServerConfig) String() string            { return proto.CompactTextString(m) }
func (*ServerConfig) ProtoMessage()               {}
func (*ServerConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServerConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerConfig) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ServerConfig) GetTls() *TLSCertificate {
	if m != nil {
		return m.Tls
	}
	return nil
}

func (m *ServerConfig) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ServerConfig) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

// deprecated
type TLSCertificate struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *TLSCertificate) Reset()                    { *m = TLSCertificate{} }
func (m *TLSCertificate) String() string            { return proto.CompactTextString(m) }
func (*TLSCertificate) ProtoMessage()               {}
func (*TLSCertificate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TLSCertificate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TLSCertificate) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// additional files referenced by the ServerConfig
type File struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type MainConfig struct {
	Config  []byte  `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Dhparam []byte  `protobuf:"bytes,2,opt,name=dhparam,proto3" json:"dhparam,omitempty"`
	Files   []*File `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
}

func (m *MainConfig) Reset()                    { *m = MainConfig{} }
func (m *MainConfig) String() string            { return proto.CompactTextString(m) }
func (*MainConfig) ProtoMessage()               {}
func (*MainConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MainConfig) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *MainConfig) GetDhparam() []byte {
	if m != nil {
		return m.Dhparam
	}
	return nil
}

func (m *MainConfig) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*ServerConfig)(nil), "pb.ServerConfig")
	proto.RegisterType((*TLSCertificate)(nil), "pb.TLSCertificate")
	proto.RegisterType((*File)(nil), "pb.File")
	proto.RegisterType((*MainConfig)(nil), "pb.MainConfig")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0x26, 0x69, 0xcd, 0xb4, 0x8a, 0x2c, 0x22, 0x4b, 0x0f, 0x12, 0x82, 0x87, 0x9c,
	0x72, 0xa8, 0x82, 0xe2, 0xc1, 0x4b, 0xd1, 0x93, 0xbd, 0x6c, 0x3d, 0x0b, 0x9b, 0x38, 0xa9, 0x8b,
	0xc9, 0x26, 0x6c, 0xc6, 0x42, 0x7f, 0xb2, 0xff, 0x42, 0xb2, 0x4d, 0xad, 0x85, 0x5e, 0xbc, 0xcd,
	0xdb, 0x99, 0xc7, 0xbe, 0xf9, 0x06, 0x4e, 0x5b, 0xaa, 0xad, 0x5a, 0x61, 0xda, 0xd8, 0x9a, 0x6a,
	0x3e, 0x68, 0xb2, 0xf8, 0x9b, 0xc1, 0x64, 0x89, 0x76, 0x8d, 0x76, 0x5e, 0x9b, 0x42, 0xaf, 0x38,
	0x07, 0xdf, 0xa8, 0x0a, 0x05, 0x8b, 0x58, 0x12, 0x4a, 0x57, 0xf3, 0x4b, 0x18, 0xe6, 0xae, 0x2b,
	0x06, 0x11, 0x4b, 0x26, 0xb2, 0x57, 0xfc, 0x1a, 0x3c, 0x2a, 0x5b, 0xe1, 0x45, 0x2c, 0x19, 0xcf,
	0x78, 0xda, 0x64, 0xe9, 0xeb, 0xcb, 0x72, 0x8e, 0x96, 0x74, 0xa1, 0x73, 0x45, 0x28, 0xbb, 0x36,
	0x4f, 0xc1, 0xaf, 0x90, 0x94, 0xf0, 0x23, 0x2f, 0x19, 0xcf, 0xa6, 0xdd, 0xd8, 0xdf, 0x1f, 0xd3,
	0x05, 0x92, 0x7a, 0x32, 0x64, 0x37, 0xd2, 0xcd, 0xf1, 0x2b, 0x08, 0x0a, 0x5d, 0x62, 0x2b, 0x02,
	0x67, 0x38, 0xe9, 0x0c, 0xcf, 0xba, 0x44, 0xb9, 0x7d, 0x9e, 0xde, 0x41, 0xf8, 0x6b, 0xe1, 0xe7,
	0xe0, 0x7d, 0xe2, 0xa6, 0x4f, 0xdb, 0x95, 0xfc, 0x02, 0x82, 0xb5, 0x2a, 0xbf, 0xd0, 0x65, 0x0d,
	0xe5, 0x56, 0x3c, 0x0c, 0xee, 0x59, 0xfc, 0x08, 0x67, 0x87, 0xf9, 0x8e, 0x2e, 0x2b, 0x60, 0x94,
	0xd7, 0x86, 0xd0, 0x50, 0xbf, 0xed, 0x4e, 0xc6, 0xb7, 0xe0, 0x77, 0x39, 0xfe, 0xe9, 0x7a, 0x03,
	0x58, 0x28, 0x6d, 0x7a, 0xbc, 0x7b, 0x94, 0xec, 0x00, 0xa5, 0x80, 0xd1, 0xfb, 0x47, 0xa3, 0xac,
	0xaa, 0x76, 0xfe, 0x5e, 0xee, 0x71, 0x78, 0x47, 0x71, 0x64, 0x43, 0x77, 0xcc, 0x9b, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x43, 0x9a, 0x10, 0x1c, 0xdd, 0x01, 0x00, 0x00,
}
