#!/usr/bin/env bash

set -eu

# Add protoc and protoc-gen-go tools to PATH
export PATH=$PWD/bin:$PATH
PROJECT=$PWD

# protobuf subpackages end in "pb"
PBUFS=$(go list ./... | grep -v /vendor | grep 'pb$')

# change into each protobuf directory
for pkg in $PBUFS ; do
  abs_path=${GOPATH}/src/${pkg}
  echo Generating $abs_path
  pushd ${abs_path} > /dev/null
  # generate protocol buffers, make other .proto files available to import
  protoc --go_out=plugins=grpc:. --grpc-gateway_out=logtostderr=true:. \
    -I$PROJECT/protoc/include \
    -I$PROJECT/vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
    -I=.:"${GOPATH}/src/" *.proto
  popd > /dev/null
done
